server:
  port: 8002
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://:3306/content-center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver