server:
  port: 8877
spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        metadata:
#          instance: aa
#          namespace: 4eef7a74-a5bd-4ee2-b770-90b209d5417f

  datasource:
    url: jdbc:mysql://39.97.173.29:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

rocketmq:
  name-server: 101.200.130.236:9876